# by default, the Ghost image will use SQLite (and thus requires no separate database container)
# we have used MySQL here merely for demonstration purposes (especially environment-variable-based configuration)

#Adapted Ghost from https://hub.docker.com/_/ghost/

version: '3.1'

services:
  datalab:
    restart: always
    build: .
    expose:
      - 9090 #changed the default request port in Contest.pm, this should match it
    ports:
      - 9091:9091 #map result port to host set in Contest.pm
    environment:
      HANDOUT: 1 #First Run 1 and 0 After... 1 cleanallfiles and remakes
      VIRTUAL_HOST: example.com
      VIRTUAL_PORT: 9090 #needs to match request port
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: you@example.com
    volumes:
      - ./datalab/:/code/
    command: ./start.sh


networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
